AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: 'Minimal example w/ secret outputs.'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
Outputs:
  sadcloudsecret:
    Description: This should trigger any secret checks
    Value: AKIAIOSFODNN7EXAMPLE
    Export:
      Name: AKIAIOSFODNN7EXAMPLE
