name: Terraform Development CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "sadcloud/**"
      - ".github/workflows/main.yaml"

env:
  TF_WORKING_DIR: "sadcloud"
  S3_CLOUD_CUSTODIAN_BUCKET_NAME: "diraht-sadcloud-cloud-custodian"
  AWS_REGION: "us-east-1"

jobs:
  terraform:
    name: "Terraform"
    permissions:
      contents: "read"
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.0"

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -no-color -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Cloud Custodian
        run: pip install c7n

      - name: Run Cloud Custodian Policies
        run: |
          cd ${{ env.TF_WORKING_DIR }}
          custodian run -s . custodian-policies.yaml

      - name: Upload Custodian Logs to S3 (Optional)
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp . s3://${{ env.S3_CLOUD_CUSTODIAN_BUCKET_NAME }}/custodian-logs/ --recursive
